### ISSUE TITLE
Starter kit?

### ISSUE THREAD

**Issue by maydere1** [davidhund/awesome-vanilla-js#17]
Hello everyone!

Do you know a good starter kit for new project.

Example: Home page, login page and bundle js packages

Sincerely

**Comment by davidhund** [comment]
Hello @maydere1 — this is hard to answer. This repository deals with 'Vanilla JS', so bare-bones and no framework by definition. It seems you are looking for the opposite: a starter 'kit' (in some framework) for a complete website. 

Which framework depends on your needs and preferred 'technology stack': for example PHP, of VueJS or React?

Have you tried searching for "site starter kit"?

Seeing that you mention various 'pages' (Home, Login) as well as 'bundles' for JS a JavaScript Framework seems what you are looking for. In that case I'd advise you to look at [NextJS](https://nextjs.org/) (React), [Nuxt](https://nuxtjs.org/) (VueJS) or [SvelteKit](https://kit.svelte.dev/) (Svelte). 

These frameworks add a 'starter' for complete (JS-based) websites that can handle login etc. 
This is, however, quite the opposite of 'Vanilla JS' :-)

Best of luck

**Comment by maydere1** [comment]
> 
> 
> Hello @maydere1 — this is hard to answer. This repository deals with 'Vanilla JS', so bare-bones and no framework by definition. It seems you are looking for the opposite: a starter 'kit' (in some framework) for a complete website.
> 
> Which framework depends on your needs and preferred 'technology stack': for example PHP, of VueJS or React?
> 
> Have you tried searching for "site starter kit"?
> 
> Seeing that you mention various 'pages' (Home, Login) as well as 'bundles' for JS a JavaScript Framework seems what you are looking for. In that case I'd advise you to look at [NextJS](https://nextjs.org/) (React), [Nuxt](https://nuxtjs.org/) (VueJS) or [SvelteKit](https://kit.svelte.dev/) (Svelte).
> 
> These frameworks add a 'starter' for complete (JS-based) websites that can handle login etc. This is, however, quite the opposite of 'Vanilla JS' :-)
> 
> Best of luck

Hi David

I am so sorry for the wrong question.

I am looking a starter kit with vanillajs. No react, vue or etc.

Pure js (vanilla) is much better, faster, easier, simpler and less dependency. Actualy, no package dependency.

I looked vanilla-starter-kit and I found just very simple app.

I am looking a good starter kit 

Best of luck
