### ISSUE TITLE
Examples on website use var in if block

### ISSUE THREAD

**Issue by nicenemo** [davidhund/awesome-vanilla-js#2]
Examples on website use `var` in if block.
Please give more appropriate examples for novice users, e.g. declare variables at function scope.

**Comment by davidhund** [comment]
Hi @nicenemo - Thanks for stopping by. 

The README in this repo simply links to other sites. I believe your issue is with code examples on one of these sites? I suggest you take this up with the site in question.

Regards, David Hund
