### ISSUE TITLE
Components section

### ISSUE THREAD

**Issue by dkniffin** [davidhund/awesome-vanilla-js#3]
Thanks for creating this repo, it's really helpful. However, I'd love to see a section on vanilla JS components. Here's a few I've found recently:

- Tooltip: https://atomiks.github.io/tippyjs/
- Modal: https://micromodal.now.sh/
- Dropdown w/ multiselect: https://slimselectjs.com/
- Another dropdown library: https://github.pytes.net/tail.select/

**Comment by davidhund** [comment]
👋🏻 Derek,
Thank you for your comment. I agree a *Components* section would be nice.

There are *many* such components, though, so it would be quite a task.
Unfortunately I cannot spend much time maintaining this repo (as you've probably noticed 😉).
PR's are always welcomed, though, so feel free.

**Comment by dkniffin** [comment]
@davidhund Makes sense. I have been working with these types of components a lot lately. I would definitely be happy to make a PR.

Edit: I've created a PR at #4

**Comment by davidhund** [comment]
Awesome 😏
Thanks 👏🏻 @dkniffin
